---

- name: "install NodeJS 13.8.0"
  become: true
  shell: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt install -y nodejs
      sudo apt install npm
      # Use n version manager to use Node.js v13.8.0
      sudo npm install --global n
      sudo n 13.8.0


- name: "install python for Ansible."
  become: true
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python3)
  changed_when: false 

- name: Install Yarn NPM package globallyy
  community.general.npm:
    name: yarn@latest
    global: true
  environment:
    PATH: /opt/nodejs/bin:{{ ansible_facts.env.PATH }}

- name: "install pm2"
  become: true
  npm:
      name: pm2
      global: yes
      production: yes



