---
- name: "Creates backend app directory"
  become: true
  file:
      path: ~/backend-app
      state: directory
- name: "Unarchive backend files"
  become: true
  unarchive:
      src: artifact.tar.gz
      dest: ~/backend-app

- name : "installing Node Dependancies"
  become: true

  shell: |
    cd ~/backend-app
    npm i
    
- name: "execute node with pm2"
  become: true

  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "print mesage"
  debug:
    msg: "{{execute_node.stdout_lines }}"

- name: "configure pm2 to start when reboot "
  shell: |
     pm2 startup 
     sudo su -c "env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
     pm2 save
     pm2 unstartup systemd
- name: make jsreport start at system restart
  become: true
  command: pm2 startup systemd -u ubuntu --hp /home/username
  environment:
   PATH: "{{ ansible_env.PATH }}"